image: "prefecthq/prefect:3.0-python3.12"

stages:
  - validate
  - test
  - deploy

validate:
  stage: validate
  script:
    # Loop over all new or modified files
    - for file in $(git diff --name-only HEAD^ HEAD); do
        # if it's deployment file then validate its content
        if [[ "$(basename "$file")" == "deployment.yaml" ]]; then
          echo "Validating deployments in: $file";
          python utils/validation/deployments.py $file;
        # if it's Python module then validate flows in it
        elif [[ "$file" == *.py ]]; then
          echo "Validating flows in: $file";
          python utils/validation/flows.py $file;
        fi;
      done;

test:
  stage: test
  script:
    # Run unit-tests
    - pytest tests -v

deploy:
  stage: deploy
  script:
    # PREFECT_API_URL needs to be set in project's Settings -> CI/CD -> Variables
    - PREFECT_API_URL=$PREFECT_API_URL
    - python --version && echo "Prefect $(prefect --version)"
    # Loop over all new or modified "deployment.yaml" files and deploy them to Prefect Server
    - for file in $(git diff --name-only HEAD^ HEAD | grep "deployment.yaml"); do
        echo "Preparing to deploy: $file";
        prefect --no-prompt deploy --prefect-file $file --all;
      done;
  only:
    - main
